### ISSUE TITLE
Infinite loop when installing plugins

### ISSUE THREAD

**Issue by noahccoker** [starkandwayne/starkandwayne-c3tk-image#2]
There is an infinite loop that is caused by calling the cf command (which is recursive in this script):

```
for plugin in "${plugins[@]}"
do
  IFS="|"
  if ! [[ "${IFS}${installed[*]}${IFS}" =~ "${IFS}${plugin}${IFS}" ]]
  then
    echo -e "Installing Plugin ${plugin}..."
    cf install-plugin -r CF-Community "${plugin}"   # <----- the recursive cf command is here
  fi
  unset IFS # or set back to original IFS if previously set
done
```

The cf command is actually calling the cf-wrapper and not the actual cf command. One suggestion that might fix this is to change `cf` in this code block to `cf7` or `/opt/bin/cf7` to alleviate the issue with the recursion. 

This does not completely fix the issue because the plugins fail to install on the m1 Mac.

**Comment by norman-abramovitz** [comment]
This issue was fixed by PR #5 by calling CF7 instead of CF
